import { scoreCard, whyFlagged, type CardInput, type Scores } from "./engine";

export const catalog: CardInput[] = [
  {
    slug: "pikachu-sp-campaign-demo",
    name: "Pikachu campaign promo",
    set: "S-P",
    number: "XXX",
    language: "JP",
    year: 2021,
    distribution: "CAMPAIGN",
    character: "Pikachu",
    promoFamily: "S-P Pikachu",
    nickname: "Campaign Pikachu",
    japanExclusive: true,
    sealedStillPrinted: false,
    price: 32,
    priceChange7d: 8,
    priceChange30d: 11,
    sales24h: 7,
    sales7d: 46,
    salesPrev7d: 18,
    sales30d: 90,
    salesPrev30d: 40,
    uniqueBuyers7d: 31,
    activeListings: 49,
    activeListings7dAgo: 81,
    activeListings30dAgo: 110,
    newListings7d: 18,
    soldListings7d: 40,
    psa10Pop: 1340,
    popGrowth30d: 2.1,
    jpPrice: 28,
    usPrice: 36,
    sellerTopShare: 0.08,
  },
  {
    slug: "umbreon-vmax-alt-demo",
    name: "Umbreon VMAX alt art",
    set: "SWSH07",
    number: "215",
    language: "EN",
    year: 2021,
    distribution: "BOOSTER",
    character: "Umbreon",
    nickname: "Moonbreon",
    illustrator: "Mitsuhiro Arita-style chase",
    sealedStillPrinted: false,
    price: 520,
    priceChange7d: 4,
    priceChange30d: 9,
    sales24h: 6,
    sales7d: 38,
    salesPrev7d: 29,
    sales30d: 140,
    salesPrev30d: 120,
    uniqueBuyers7d: 27,
    activeListings: 22,
    activeListings7dAgo: 30,
    activeListings30dAgo: 41,
    newListings7d: 16,
    soldListings7d: 24,
    psa10Pop: 9800,
    popGrowth30d: 1.4,
    jpPrice: 390,
    usPrice: 520,
    sellerTopShare: 0.05,
  },
  {
    slug: "charizard-upc-demo",
    name: "Charizard UPC promo",
    set: "SWSH",
    number: "UPC",
    language: "EN",
    year: 2022,
    distribution: "SPECIAL_BOX",
    character: "Charizard",
    sealedStillPrinted: true,
    price: 78,
    priceChange7d: 22,
    priceChange30d: 48,
    sales24h: 4,
    sales7d: 19,
    salesPrev7d: 11,
    sales30d: 50,
    salesPrev30d: 28,
    uniqueBuyers7d: 14,
    activeListings: 60,
    activeListings7dAgo: 44,
    activeListings30dAgo: 40,
    newListings7d: 28,
    soldListings7d: 15,
    psa10Pop: 6200,
    popGrowth30d: 6.4,
    usPrice: 78,
    sellerTopShare: 0.12,
  },
  {
    slug: "rayquaza-pc-demo",
    name: "Rayquaza Pokémon Center promo",
    set: "SV-P",
    number: "PC",
    language: "JP",
    year: 2024,
    distribution: "POKEMON_CENTER",
    character: "Rayquaza",
    promoFamily: "SV-P",
    japanExclusive: true,
    sealedStillPrinted: false,
    price: 64,
    priceChange7d: 6,
    priceChange30d: 9,
    sales24h: 3,
    sales7d: 21,
    salesPrev7d: 9,
    sales30d: 34,
    salesPrev30d: 16,
    uniqueBuyers7d: 16,
    activeListings: 14,
    activeListings7dAgo: 27,
    activeListings30dAgo: 33,
    newListings7d: 6,
    soldListings7d: 17,
    psa10Pop: 410,
    popGrowth30d: 1.1,
    jpPrice: 48,
    usPrice: 71,
    sellerTopShare: 0.09,
  },
  {
    slug: "gengar-mascot-demo",
    name: "Gengar mascot promo",
    set: "S-P",
    number: "GEN",
    language: "JP",
    year: 2020,
    distribution: "EVENT_PROMO",
    character: "Gengar",
    japanExclusive: true,
    sealedStillPrinted: false,
    price: 140,
    priceChange7d: 3,
    priceChange30d: 5,
    sales24h: 1,
    sales7d: 8,
    salesPrev7d: 3,
    sales30d: 14,
    salesPrev30d: 7,
    uniqueBuyers7d: 7,
    activeListings: 6,
    activeListings7dAgo: 11,
    activeListings30dAgo: 12,
    newListings7d: 2,
    soldListings7d: 7,
    psa10Pop: 180,
    popGrowth30d: 0.6,
    jpPrice: 110,
    usPrice: 155,
    sellerTopShare: 0.2,
  },
];

export type ScoutCard = CardInput & { scores: Scores; why: string[] };

export function scoredCatalog(): ScoutCard[] {
  return catalog.map((c) => {
    const scores = scoreCard(c);
    return { ...c, scores, why: whyFlagged(c, scores) };
  });
}

export function bySlug(slug: string) {
  return scoredCatalog().find((c) => c.slug === slug) ?? null;
}

export function watchlist(kind: string) {
  const rows = scoredCatalog();
  if (kind === "early") return rows.filter((c) => c.scores.stage === 1 || c.scores.stage === 2);
  if (kind === "breakout") return rows.filter((c) => c.scores.stage === 3);
  if (kind === "pikachu") return rows.filter((c) => c.character === "Pikachu");
  if (kind === "promo") return rows.filter((c) => c.distribution !== "BOOSTER");
  if (kind === "japan") return rows.filter((c) => c.language === "JP" && (c.jpPrice ?? 0) > 0);
  if (kind === "supply") return rows.filter((c) => c.activeListings < c.activeListings7dAgo * 0.75);
  return rows;
}
